---

- hosts: all
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  - name: add php to support apache
    apt:
      name: libapache2-mod-php
      state: latest
#become is equivalent to sudo.
#we determine the apt module.
#and name is the package name that we want to install.
#state: we can say latest to get the latest version of a package, or absent to remove it.

