---
- hosts: elk
  become: true
  tasks:
  
  - name: install unzip
    apt:
      update_cache: yes
      name: unzip
      state: latest


  - name: install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
#remote_src: to download the file from remote host
