---

- hosts: all
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
  - name: add php to support apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: install apache on Centos distros
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8"

  - name: install php on Centos distros
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"


#become is equivalent to sudo.
#we determine the apt module.
#and name is the package name that we want to install.
#state: we can say latest to get the latest version of a package, or absent to remove it.
#we can use when against every variable in gather_facts module

