---
- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache(Debian)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: workstations
  become: true
  roles:
    - workstations
    
- hosts:
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
