---
- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Debian)
    tags: updates,Debian
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"
 
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install apache and php for Debian servers
    tags: apache2,apache,Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
 
  - name: install apache and php for CentOS servers
    tags: httpd,apache,CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

#pre_tasks a way to mandate that something need to run first .
